remove manual edit from compute_json1_diff method
tillmo/erpnext-client pull request #35
Opened 2023-06-18 11:50 UTC by Andrewed95

2023-06-18 14:42 UTC, tillmo requested changes
`manual_edit` works fine. However, items are still missing for PreR00604

2023-06-18 15:01 UTC, Andrewed95 commented
> `manual_edit` works fine. However, items are still missing for PreR00604

Would you please send me the result you see in the jsoneditor view?

2023-06-19 12:42 UTC, Andrewed95 commented
> `manual_edit` works fine. However, items are still missing for PreR00604

Pushed some changes. Please try again.

2023-06-19 13:26 UTC, tillmo approved these changes

2023-06-19 16:07 UTC, merged